#ifndef KEYS_HPP
#define KEYS_HPP

#include "SFML/Window/Event.hpp"

namespace engine{
	/// \brief Enumeration of the different mouse buttons
	enum MouseButton{
		LeftButton = sf::Mouse::Left,     
		RightButton = sf::Mouse::Right,    
		MiddleButton = sf::Mouse::Middle,   
		X1Button = sf::Mouse::XButton1, 
		X2Button = sf::Mouse::XButton2, 
	};

	/// \brief Enumeration of the different Keyboard keys
	enum Key{
		A			= sf::Key::A,
		B			= sf::Key::B,
		C			= sf::Key::C,
		D			= sf::Key::D,
		E			= sf::Key::E,
		F			= sf::Key::F,
		G			= sf::Key::G,
		H			= sf::Key::H,
		I			= sf::Key::I,
		J			= sf::Key::J,
		K			= sf::Key::K,
		L			= sf::Key::L,
		M			= sf::Key::M,
		N			= sf::Key::N,
		O			= sf::Key::O,
		P			= sf::Key::P,
		Q			= sf::Key::Q,
		R			= sf::Key::R,
		S			= sf::Key::S,
		T			= sf::Key::T,
		U			= sf::Key::U,
		V			= sf::Key::V,
		X			= sf::Key::X,
		Y			= sf::Key::Y,
		Z			= sf::Key::Z,
		Num0		= sf::Key::Num0,
		Num1		= sf::Key::Num1,
		Num2		= sf::Key::Num2,
		Num3		= sf::Key::Num3,
		Num4		= sf::Key::Num4,
		Num5		= sf::Key::Num5,
		Num6		= sf::Key::Num6,
		Num7		= sf::Key::Num7,
		Num8		= sf::Key::Num8,
		Num9		= sf::Key::Num9,
		Escape		= sf::Key::Escape,
		LShift		= sf::Key::LShift,
		LControl	= sf::Key::LControl,
		LAlt		= sf::Key::LAlt,
		LSystem		= sf::Key::LSystem,
		RShift		= sf::Key::RShift,
		RAlt		= sf::Key::RAlt,
		RControl	= sf::Key::RControl,
		RSystem		= sf::Key::RSystem,
		Menu		= sf::Key::Menu,
		LBracket	= sf::Key::LBracket,
		RBracket	= sf::Key::RBracket,
		SemiColon	= sf::Key::SemiColon,
		Comma		= sf::Key::Comma,
		Period		= sf::Key::Period,
		Quote		= sf::Key::Quote,
		Slash		= sf::Key::Slash,
		BackSlash	= sf::Key::BackSlash,
		Tilde		= sf::Key::Tilde,
		Equal		= sf::Key::Equal,
		Dash		= sf::Key::Dash,
		Space		= sf::Key::Space,
		Return		= sf::Key::Return,
		Back		= sf::Key::Back,
		Tab			= sf::Key::Tab,
		PageUp		= sf::Key::PageUp,
		PageDown	= sf::Key::PageDown,
		End			= sf::Key::End,
		Home		= sf::Key::Home,
		Insert		= sf::Key::Insert,
		Delete		= sf::Key::Delete,
		Add			= sf::Key::Add,
		Subtract	= sf::Key::Subtract,
		Multiply	= sf::Key::Multiply,
		Divide		= sf::Key::Divide,
		Left		= sf::Key::Left,
		Right		= sf::Key::Right,
		Up			= sf::Key::Up,
		Down		= sf::Key::Down,
		Numpad0		= sf::Key::Numpad0,
		Numpad1		= sf::Key::Numpad1,
		Numpad2		= sf::Key::Numpad2,
		Numpad3		= sf::Key::Numpad3,
		Numpad4		= sf::Key::Numpad4,
		Numpad5		= sf::Key::Numpad5,
		Numpad6		= sf::Key::Numpad6,
		Numpad7		= sf::Key::Numpad7,
		Numpad8		= sf::Key::Numpad8,
		Numpad9		= sf::Key::Numpad9,
		F1			= sf::Key::F1,
		F2			= sf::Key::F2,
		F3			= sf::Key::F3,
		F4			= sf::Key::F4,
		F5			= sf::Key::F5,
		F6			= sf::Key::F6,
		F7			= sf::Key::F7,
		F8			= sf::Key::F8,
		F9			= sf::Key::F9,
		F10			= sf::Key::F10,
		F11			= sf::Key::F11,
		F12			= sf::Key::F12,
		Pause		= sf::Key::Pause,
	};
}
#endif
